#!/bin/sh

echo "FIXING CONFIG!!!!!!!"
CPU_TEST=`lscpu | grep Intel`
CPU_COMMENT=""
VIRT_YES=""
if [[ -z $CPU_TEST ]]; then
    CPU_COMMENT="CPU_SUP_INTEL"
else
    CPU_COMMENT="CPU_SUP_AMD"
fi

VIRT_TEST=`hostnamectl | grep "computer-vm"`
VIRT_COMMENT=""
if [[ -z $VIRT_TEST ]]; then
    VIRT_COMMENT="HYPERVISOR_GUEST VIRT_DRIVERS VIRTIO_MENU DRM_VBOXVIDEO"
    VIRT_YES="STAGING"
else
    VIRT_COMMENT="WLAN WIRELESS"
fi

COMMENT_LIST="RCU_FAST_NO_HZ BPFILTER XEN EXPERT RESET_CONTROLLER AGP RANDOMIZE_BASE CRASH_DUMP KEXEC SFI APPLE_PROPERTIES DRM_RADEON NET_CADENCE NET_PACKET_ENGINE SERIAL_8250 SECURITY SECURITYFS KPROBES PROFILING DW_DMAC ATA_VERBOSE_ERROR SATA_ZPODD SATA_ACARD_AHCI INPUT_MISC SERIAL_8250_RT288x AUXDISPLAY ACCESSIBILITY TASKSTATS PM_DEBUG PM_TRACE_RTC IP_ADVANCED_ROUTER PRINTK_TIME STACKTRACE PARTITION_ADVANCED NET_SCHED MPLS IP_MROUTE IPV6_MROUTE IPV6_ROUTER_PREF IPV6_OPTIMISTIC_DAD IPV6_SUBTREES IPV6_SEG6_LWTUNNEL IPV6_SEG6_HMAC SYN_COOKIES IP_MULTICAST TCP_CONG_ADVANCED TCP_MD5SIG CDROM_PKTCDVD QUOTA OVERLAY_FS FTRACE EARLY_PRINTK_EFI UNUSED_SYMBOLS DEBUG_FS FRAME_POINTER CRYPTO_HW SCSI_LOWLEVEL SCSI_DH SERIAL_NONSTANDARD CHROME_PLATFORMS NETFILTER GART_IOMMU CALGARY_IOMMU KERNEL_GZIP IO_DELAY_0X80 GENERIC_CPU TRACING_SUPPORT MAGIC_SYSRQ DEBUG_KERNEL BXT_WC_PMIC_OPREGION CRC_PMIC_OPREGION SND_VERBOSE_PROCFS SND_USB SND_X86 SND_DRIVERS SND_SPI VIRTUALIZATION ISDN MACINTOSH_DRIVERS FUSION HAMRADIO GENERIC_CPU PARPORT LEGACY_VSYSCALL_EMULATE CPUSETS CGROUP_PERF MODVERSIONS BLK_DEV_BSGLIB X86_AMD_PLATFORM_DEVICE X86_MCE_AMD AMD_MEM_ENCRYPT AMD_NUMA ARCH_MEMORY_PROBE ZONE_DEVICE KEXEC_FILE SCHED_DEBUG SCHED_STACK_END_CHECK DEBUG_PREEMPT DEBUG_BUGVERBOSE SLUB_DEBUG KERNEL_XZ ACPI_DEBUG ACPI_EC_DEBUGFS PNP_DEBUG_MESSAGES DEBUG_MEMORY_INIT HZ_1000 STAGING_MEDIA STAGING_BOARD UNISYSSPAR CPU_SUP_CENTAUR MELLANOX_PLATFORM SOUNDWIRE SOC_TI CHECKPOINT_RESTORE BLK_DEV_INTEGRITY BLK_DEV_ZONED $CPU_COMMENT $VIRT_COMMENT"

for i in $COMMENT_LIST
do
    sed -i "/^CONFIG_${i}=/c\# CONFIG_${i} is not set" .config
done

YES_LIST="LEGACY_VSYSCALL_NONE FB_SIMPLE NTFS_RW TRIM_UNUSED_KSYMS X86_P6_NOP KERNEL_LZ4 IO_DELAY_NONE MNATIVE OPTIMIZE_INLINING NLS_ASCII NLS_CODEPAGE_437 NLS_UTF8 HZ_300 $VIRT_YES"

for i in $YES_LIST
do
    sed -i "/# CONFIG_${i} is not set/c\CONFIG_${i}=y" .config
done

MODULE_LIST="HID ISO9660_FS RAPL DRM_VMWGFX DRM_VIRTIO_GPU BTRFS_FS FB_HYPERV NLS_ISO8859_1 NLS_ISO8859_15 MSDOS_FS VFAT_FS EXFAT_FS NTFS_FS USB_STORAGE IPV6 INET6_AH INET6_IPCOMP INET6_XFRM_MODE_TRANSPORT INET6_XFRM_MODE_TUNNEL INET6_XFRM_MODE_BEET INET6_XFRM_MODE_ROUTEOPTIMIZATION INET6_ATT INET6_ESP IPV6_VTI IPV6_SIT CRC_ITU_T CRC7 LIBCRC32C CRC8 CORDIC ACPI_THERMAL HYPERV HYPERV_UTILS VIRTIO_PCI BLK_DEV_SD MQ_IOSCHED_BFQ X86_MSR X86_CPUID"

for i in $MODULE_LIST
do
    sed -i "/# CONFIG_${i} is not set/c\CONFIG_${i}=m" .config
done

sed -i "s/CONFIG_DEFAULT_IO_DELAY_TYPE=0/CONFIG_DEFAULT_IO_DELAY_TYPE=3/" .config

sed -i "/CONFIG_NODES_SHIFT=/c\CONFIG_NODES_SHIFT=3" .config

sed -i "/CONFIG_NR_CPUS=/c\CONFIG_NR_CPUS=5" .config

lead='^\#\ Crypto\ core\ or\ helper'
tail='^\#\ Certificates\ for\ signature\ checking'
sed -n "/$lead/,/$tail/p" ../config > blah.txt
sed -i "/$lead/,/$tail/{ /$lead/{p; r blah.txt
        }; /$tail/p; d }" .config

sed -i "/^CONFIG_NET_VENDOR/s/=y/=n/" .config
sed -i "s/CONFIG_NET_VENDOR_INTEL=n/CONFIG_NET_VENDOR_INTEL=y/" .config

sed -i "/^# CONFIG_NLS_/s/ is not set/=m/" .config
sed -i "/^# CONFIG_NLS_/s/# //" .config
sed -i "s/CONFIG_HZ=1000/CONFIG_HZ=300/" .config
